// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbruxmwivlpzethqyjru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZicnV4bXdpdmxwemV0aHF5anJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzgzMjIsImV4cCI6MjA2ODE1NDMyMn0.4xBU-69X2u4HoBTm3I2uzX4ra8ZU5urrnCOby404qbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});